name: Hovercards Package Size

on:
  pull_request:
    paths:
      - 'web/packages/hovercards/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up working directory
        run: cd web/packages/hovercards

      - uses: actions/checkout@v4
      - uses: preactjs/compressed-size-action@v2
