name: Quick Editor Package Size

on:
  pull_request:
    paths:
      - 'web/packages/quick-editor/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: preactjs/compressed-size-action@v2
        with:
          cwd: web/packages/quick-editor
